### ISSUE TITLE
使用scaffold指令 建立範例後 沒有建立 line_controller.rb

### ISSUE THREAD

**Issue by WolsYang** [etrex/kamigo#2]
使用 以下指令後
rails new kamigo_demo
cd kamigo_demo
bundle add kamigo
bundle add dotenv-rails
rails g scaffold todo name desc
rails db:create
rails db:migrate

沒有建立 line_controller.rb
不知道是不是我有地方操作錯了

**Comment by louis70109** [comment]
> rails g scaffold todo name desc
你執行這行指令會建立出 todos_controller.rb
並沒有 line_controller.rb 哦！

而你打 `rails routes` 會看到有一個 `/line` 的路由是套件幫你生成的

**Comment by WolsYang** [comment]
> rails routes
好的  我以為是會直接幫忙建完
謝謝

**Comment by etrex** [comment]
line_controller 在套件內，你不需要看見他

**Comment by WolsYang** [comment]
收到  更了解運作了感謝：）
